package com.example.studytime.domain.model

import androidx.compose.ui.graphics.Color
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.example.studytime.presentation.theme.gradient1
import com.example.studytime.presentation.theme.gradient2
import com.example.studytime.presentation.theme.gradient3
import com.example.studytime.presentation.theme.gradient4
import com.example.studytime.presentation.theme.gradient5

@Entity // telling database that this Subject class is an entity
data class Subject(
    val name: String,
    val goalHours: Float,
    val colors: List<Int>,
    val imagePath: String?,

    @PrimaryKey(autoGenerate = true) //allocate subjectId as primary key (autogenerated)
    val subjectId: Int? = null
){
    companion object{
        val subjectCardColors = listOf(gradient1, gradient2, gradient3, gradient4, gradient5)
    }
}
