package com.example.studytime.domain.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity // telling database that this Task class is an entity
data class Task(
    val title: String,
    val description: String,
    val dueDate: Long,
    val priority: Int,
    val relatedToSubject: String,
    val isComplete: Boolean,
    val taskSubjectId: Int,

    @PrimaryKey(autoGenerate = true) //allocate TaskId as primary key (autogenerated)
    val taskId: Int? = null
)
